-- cod_points: titik COD aman DKI Jakarta (flat, tanpa normalisasi)
-- 126 titik = 42 kecamatan x 3, 5 kota administrasi. Sumber: COD_POINTS.md
-- Jam operasional diseragamkan 07.00-21.00 WIB (keputusan Blok 1).
-- safety_score: scoring statis 0-3 (bukan klaim "aman"); default 2 = lolos
-- checklist, 3 = anchor dgn CCTV+petugas melekat (stasiun/mal/bandara/RS).
-- Ganti dengan skor riset bila ada data per titik.

create table if not exists public.cod_points (
  id uuid primary key default gen_random_uuid(),
  kota text not null,
  kecamatan text not null,
  nama text not null,
  safety_score int not null default 2 check (safety_score between 0 and 3),
  operating_hours text not null default '07.00-21.00 WIB',
  created_at timestamptz not null default now(),
  unique (kota, kecamatan, nama)
);

create index if not exists cod_points_lokasi_idx on public.cod_points (kota, kecamatan);

alter table public.cod_points enable row level security;

drop policy if exists "cod_points public read" on public.cod_points;
create policy "cod_points public read" on public.cod_points
  for select using (true);
-- tanpa policy insert/update/delete: hanya service role (default deny anon)

insert into public.cod_points (kota, kecamatan, nama, safety_score) values
('Jakarta Selatan', 'Mampang Prapatan', 'Lippo Mall Kemang (Lobby)', 3),
('Jakarta Selatan', 'Mampang Prapatan', 'Halte TJ Mampang Prapatan', 2),
('Jakarta Selatan', 'Mampang Prapatan', 'SPBU Shell Tendean', 2),
('Jakarta Selatan', 'Pancoran', 'Kalibata City Square (Lobby)', 3),
('Jakarta Selatan', 'Pancoran', 'Stasiun Duren Kalibata (Pintu Timur)', 3),
('Jakarta Selatan', 'Pancoran', 'Patung Pancoran (Area Terang/Polisi)', 2),
('Jakarta Selatan', 'Cilandak', 'Cilandak Town Square (Citos)', 3),
('Jakarta Selatan', 'Cilandak', 'Stasiun MRT Fatmawati', 3),
('Jakarta Selatan', 'Cilandak', 'One Belpark Mall', 3),
('Jakarta Selatan', 'Jagakarsa', 'AEON Mall Tanjung Barat', 3),
('Jakarta Selatan', 'Jagakarsa', 'Stasiun Lenteng Agung', 3),
('Jakarta Selatan', 'Jagakarsa', 'SPBU Pertamina 31.126.01', 2),
('Jakarta Selatan', 'Kebayoran Baru', 'Blok M Plaza (Lobby/MRT)', 3),
('Jakarta Selatan', 'Kebayoran Baru', 'Senayan City', 2),
('Jakarta Selatan', 'Kebayoran Baru', 'Pacific Place', 2),
('Jakarta Selatan', 'Kebayoran Lama', 'Pondok Indah Mall (PIM)', 3),
('Jakarta Selatan', 'Kebayoran Lama', 'Gandaria City', 2),
('Jakarta Selatan', 'Kebayoran Lama', 'Stasiun Kebayoran', 3),
('Jakarta Selatan', 'Pasar Minggu', 'The Park Pejaten', 2),
('Jakarta Selatan', 'Pasar Minggu', 'Stasiun Pasar Minggu', 3),
('Jakarta Selatan', 'Pasar Minggu', 'Terminal Pasar Minggu', 2),
('Jakarta Selatan', 'Pesanggrahan', 'Bintaro Jaya Xchange (Lobby)', 2),
('Jakarta Selatan', 'Pesanggrahan', 'SPBU Pertamina 34.122.04 (Veteran)', 2),
('Jakarta Selatan', 'Pesanggrahan', 'Universitas Tanri Abeng', 2),
('Jakarta Selatan', 'Setiabudi', 'Lotte Shopping Avenue', 2),
('Jakarta Selatan', 'Setiabudi', 'Kuningan City', 2),
('Jakarta Selatan', 'Setiabudi', 'Plaza Festival', 3),
('Jakarta Selatan', 'Tebet', 'Kota Kasablanka (Kokas)', 2),
('Jakarta Selatan', 'Tebet', 'Tebet Eco Park (Main Gate)', 2),
('Jakarta Selatan', 'Tebet', 'Stasiun Tebet', 3),
('Jakarta Pusat', 'Tanah Abang', 'Grand Indonesia (Lobby)', 2),
('Jakarta Pusat', 'Tanah Abang', 'Stasiun Tanah Abang', 3),
('Jakarta Pusat', 'Tanah Abang', 'Citywalk Sudirman', 2),
('Jakarta Pusat', 'Menteng', 'Stasiun Gondangdia', 3),
('Jakarta Pusat', 'Menteng', 'Taman Menteng', 2),
('Jakarta Pusat', 'Menteng', 'Plaza Menteng', 3),
('Jakarta Pusat', 'Senen', 'Plaza Atrium Senen', 3),
('Jakarta Pusat', 'Senen', 'Stasiun Senen (Hall Depan)', 3),
('Jakarta Pusat', 'Senen', 'Terminal Senen', 2),
('Jakarta Pusat', 'Johar Baru', 'Pasar Johar Baru', 2),
('Jakarta Pusat', 'Johar Baru', 'SPBU Galur (Suprapto)', 2),
('Jakarta Pusat', 'Johar Baru', 'Halte TJ Galur', 2),
('Jakarta Pusat', 'Cempaka Putih', 'Green Pramuka Square', 3),
('Jakarta Pusat', 'Cempaka Putih', 'Transmart Cempaka Putih', 2),
('Jakarta Pusat', 'Cempaka Putih', 'Holland Bakery Cempaka Putih', 2),
('Jakarta Pusat', 'Kemayoran', 'MGK Kemayoran', 2),
('Jakarta Pusat', 'Kemayoran', 'JIExpo (Pintu Utama)', 3),
('Jakarta Pusat', 'Kemayoran', 'Stasiun Kemayoran', 3),
('Jakarta Pusat', 'Sawah Besar', 'Gerbang Utama Pasar Baru', 2),
('Jakarta Pusat', 'Sawah Besar', 'Stasiun Juanda', 3),
('Jakarta Pusat', 'Sawah Besar', 'Harco Mangga Dua', 2),
('Jakarta Pusat', 'Gambir', 'Stasiun Gambir (Hall/Parkir)', 3),
('Jakarta Pusat', 'Gambir', 'Monas (Parkir IRTI)', 2),
('Jakarta Pusat', 'Gambir', 'Gajah Mada Plaza', 3),
('Jakarta Utara', 'Kelapa Gading', 'Mall Kelapa Gading (MKG)', 3),
('Jakarta Utara', 'Kelapa Gading', 'Stasiun LRT Boulevard Utara', 3),
('Jakarta Utara', 'Kelapa Gading', 'Mal Artha Gading', 2),
('Jakarta Utara', 'Penjaringan', 'Emporium Pluit Mall', 3),
('Jakarta Utara', 'Penjaringan', 'Pluit Village', 2),
('Jakarta Utara', 'Penjaringan', 'PIK Avenue', 2),
('Jakarta Utara', 'Tanjung Priok', 'Terminal Tanjung Priok', 2),
('Jakarta Utara', 'Tanjung Priok', 'Sunter Mall', 3),
('Jakarta Utara', 'Tanjung Priok', 'Jakarta International Stadium (JIS)', 3),
('Jakarta Utara', 'Cilincing', 'Pasar Cilincing', 2),
('Jakarta Utara', 'Cilincing', 'Rusun Marunda (Security Post)', 2),
('Jakarta Utara', 'Cilincing', 'SPBU Pertamina 34.141.01', 2),
('Jakarta Utara', 'Koja', 'Mall Koja Trade Center', 3),
('Jakarta Utara', 'Koja', 'Islamic Centre Jakarta', 2),
('Jakarta Utara', 'Koja', 'Stasiun Tanjung Priok (Sisi Timur)', 3),
('Jakarta Utara', 'Pademangan', 'Gerbang Utama Ancol', 2),
('Jakarta Utara', 'Pademangan', 'Stasiun Ancol', 3),
('Jakarta Utara', 'Pademangan', 'WTC Mangga Dua', 2),
('Jakarta Barat', 'Cengkareng', 'Mall Taman Palem', 3),
('Jakarta Barat', 'Cengkareng', 'RSUD Cengkareng', 3),
('Jakarta Barat', 'Cengkareng', 'Halte TJ Rawa Buaya', 2),
('Jakarta Barat', 'Grogol Petamburan', 'Mall Ciputra (Citraland)', 3),
('Jakarta Barat', 'Grogol Petamburan', 'Stasiun Grogol', 3),
('Jakarta Barat', 'Grogol Petamburan', 'Terminal Grogol', 2),
('Jakarta Barat', 'Kalideres', 'Terminal Kalideres', 2),
('Jakarta Barat', 'Kalideres', 'Hari Hari Swalayan Kalideres', 2),
('Jakarta Barat', 'Kalideres', 'SPBU Daan Mogot KM 17', 2),
('Jakarta Barat', 'Kebon Jeruk', 'Halte TJ Kebon Jeruk', 2),
('Jakarta Barat', 'Kebon Jeruk', 'McDonald''s Kebon Jeruk (24 jam)', 2),
('Jakarta Barat', 'Kebon Jeruk', 'MNC Studios', 2),
('Jakarta Barat', 'Kembangan', 'Lippo Mall Puri', 3),
('Jakarta Barat', 'Kembangan', 'Kantor Walikota Jakarta Barat', 2),
('Jakarta Barat', 'Kembangan', 'Pasar Puri Indah', 2),
('Jakarta Barat', 'Palmerah', 'Stasiun Palmerah', 3),
('Jakarta Barat', 'Palmerah', 'Plaza Slipi Jaya', 3),
('Jakarta Barat', 'Palmerah', 'Universitas Binus (Kampus Anggrek)', 2),
('Jakarta Barat', 'Taman Sari', 'Stasiun Jakarta Kota', 3),
('Jakarta Barat', 'Taman Sari', 'Glodok Plaza', 3),
('Jakarta Barat', 'Taman Sari', 'Museum Fatahillah (Kota Tua)', 2),
('Jakarta Barat', 'Tambora', 'Seasons City Mall', 3),
('Jakarta Barat', 'Tambora', 'Stasiun Angke', 3),
('Jakarta Barat', 'Tambora', 'Pasar Pagi Tambora', 2),
('Jakarta Timur', 'Cakung', 'Stasiun Cakung', 3),
('Jakarta Timur', 'Cakung', 'Terminal Pulogebang', 2),
('Jakarta Timur', 'Duren Sawit', 'Mall Cipinang Indah', 3),
('Jakarta Timur', 'Duren Sawit', 'Halte TJ Kalimalang', 2),
('Jakarta Timur', 'Duren Sawit', 'Pegadaian Pondok Kelapa Raya', 2),
('Jakarta Timur', 'Jatinegara', 'Stasiun Jatinegara', 3),
('Jakarta Timur', 'Jatinegara', 'Pasar Mester', 2),
('Jakarta Timur', 'Jatinegara', 'Terminal Kampung Melayu', 2),
('Jakarta Timur', 'Kramat Jati', 'Pasar Induk Kramat Jati', 2),
('Jakarta Timur', 'Kramat Jati', 'Halte TJ Kramat Jati', 2),
('Jakarta Timur', 'Makasar', 'Terminal Pinang Ranti', 2),
('Jakarta Timur', 'Makasar', 'Stasiun LRT Taman Mini', 3),
('Jakarta Timur', 'Makasar', 'Bandara Halim Perdanakusuma', 3),
('Jakarta Timur', 'Matraman', 'Stasiun Matraman', 3),
('Jakarta Timur', 'Matraman', 'Halte TJ Matraman 1/2', 2),
('Jakarta Timur', 'Matraman', 'Pasar Genjing', 2),
('Jakarta Timur', 'Pasar Rebo', 'Halte Flyover Raya Bogor', 2),
('Jakarta Timur', 'Pasar Rebo', 'Terminal Pasar Rebo', 2),
('Jakarta Timur', 'Pasar Rebo', 'RSUD Pasar Rebo', 3),
('Jakarta Timur', 'Pulo Gadung', 'Terminal Pulo Gadung', 2),
('Jakarta Timur', 'Pulo Gadung', 'Arion Mall', 3),
('Jakarta Timur', 'Pulo Gadung', 'GOR Rawamangun', 2),
('Jakarta Timur', 'Ciracas', 'Terminal Kampung Rambutan', 2),
('Jakarta Timur', 'Ciracas', 'Stasiun LRT Ciracas', 3),
('Jakarta Timur', 'Ciracas', 'Stasiun LRT Kampung Rambutan', 3),
('Jakarta Timur', 'Cipayung', 'Gerbang Utama TMII', 2),
('Jakarta Timur', 'Cipayung', 'RSUD Cipayung', 3)
on conflict (kota, kecamatan, nama) do nothing;
